CREATE TABLE Orders (
	OrderID INT IDENTITY,
	CustomerID INT NOT NULL
)

CREATE TABLE Customers (
	CustomerID INT IDENTITY,
	Name VARCHAR(50) NOT NULL,
	Birthday DATE NOT NULL,
	CityID INT NOT NULL
)

CREATE TABLE Cities (
	CityID INT IDENTITY,
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE OrderItems (
	OrderID INT NOT NULL,
	ItemID INT NOT NULL
)

CREATE TABLE Items (
	ItemID INT IDENTITY,
	Name VARCHAR(50) NOT NULL,
	ItemTypeID INT NOT NULL
)

CREATE TABLE ItemTypes (
	ItemTypeID INT IDENTITY,
	Name VARCHAR(50) NOT NULL
)

ALTER TABLE Orders
ADD CONSTRAINT PK_Orders
PRIMARY KEY (OrderID)

ALTER TABLE Customers
ADD CONSTRAINT PK_Customers
PRIMARY KEY (CustomerID)

ALTER TABLE Cities
ADD CONSTRAINT PK_Cities
PRIMARY KEY (CityID)

ALTER TABLE Items
ADD CONSTRAINT PK_Items
PRIMARY KEY (ItemID)

ALTER TABLE ItemTypes
ADD CONSTRAINT PK_ItemTypes
PRIMARY KEY (ItemTypeID)

ALTER TABLE OrderItems
ADD CONSTRAINT PK_OrderItems
PRIMARY KEY (OrderID, ItemID)

ALTER TABLE Orders
ADD CONSTRAINT FK_Orders_Customer
FOREIGN KEY (CustomerID)
REFERENCES Customers(CustomerID)

ALTER TABLE Customers
ADD CONSTRAINT FK_Customers_City
FOREIGN KEY (CityID)
REFERENCES Cities(CityID)

ALTER TABLE OrderItems
ADD CONSTRAINT FK_OrderItems_Order
FOREIGN KEY (OrderID)
REFERENCES Orders(OrderID)

ALTER TABLE OrderItems
ADD CONSTRAINT FK_OrderItems_Item
FOREIGN KEY (ItemID)
REFERENCES Items(ItemID)

ALTER TABLE Items
ADD CONSTRAINT FK_Items_ItemType
FOREIGN KEY (ItemTypeID)
REFERENCES ItemTypes(ItemTypeID)
